### ISSUE TITLE
NPE when Ropes+ is paired with MiniCreatures

### ISSUE THREAD

**Issue by Techokami** [kihira/MiniCreatures#1]
It happens with onEntitySpawn, related to the arrows that can stick into mobs and do things.
[Here's the log.](http://paste.ee/p/EY89U) Thank you for your hard work! I'd really like to get this mod running on my server because I think it will help improve the atmosphere :)

**Comment by kihira** [comment]
Danke! Just to note, this mod is still a rather alpha/beta stage so any issues/bugs you notice, please let me know :D I should have this fixed up for the first official alpha/beta release soon
